---
# Build definition for Concourse.cii
resources:
- name: terraform-provider-gateway-git
  type: git
  icon: github
  source:
    uri: https://github.com/mt5225/terraform-provider-gateway.git

- name: golang-1.16.x-image
  type: registry-image
  icon: docker
  source:
    repository: golang
    tag: 1.16.0-buster

task-config: &task-config
  platform: linux
  inputs:
    - name: terraform-provider-gateway-git
      path: terraform-provider-gateway
  run:
    path: /bin/sh
    args:
      - -c
      - |
        GOPATH=$PWD/go
        GW_ENDPOINT=http://localhost:5000
        cd terraform-provider-gateway
        make test 
        make vet
        make

jobs:
- name: build-provider
  public: true
  plan:
    - get: terraform-provider-gateway-git 
      trigger: true
    - get: golang-1.16.x-image
      trigger: true
    - task: run-tests
      image: golang-1.16.x-image
      config:
        << : *task-config
        