---
# Build definition for Concourse.cii
resources:
- name: tf-git
  type: git
  icon: github
  source:
    uri: https://github.com/mt5225/terraform-provider-gateway.git

- name: golang-1.16.x-image
  type: registry-image
  icon: docker
  source:
    repository: golang
    tag: 1.16-stretch

task-config: &task-config
  platform: linux
  inputs:
    - name: tf-git
      path: go/src/github.com/terraform-provider-gateway
  run:
    path: /bin/sh
    args:
      - -c
      - |
        GOPATH=$PWD/go
        cd go/src/github.com/terraform-provider-gateway
        make install

jobs:
- name: build
  public: true
  plan:
    - get: tf-git
      trigger: true
    - get: golang-1.16.x-image
      trigger: true
    - task: run-tests
      image: golang-1.16.x-image
      config:
        << : *task-config
        