---
# Build definition for Concourse.ci
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
  - name: terraform-provider-gateway

run:
  path: ./terraform-provider-gateway/ci/run-tests.sh
